### ISSUE TITLE
The client cannot patch the latest version

### ISSUE THREAD

**Issue by huanged** [yangyuan/hearthrock#83]
Program crashed after click patch

**Comment by huanged** [comment]
I tried to use this code to decrypt the dlls, https://gist.github.com/yangyuan/14444ccbc08517f64b31cf24165fccf2. I was only able to decrypt Assembly-CSharp-firstpass.dll & Assembly-UnityScript.dll, failed to decrypt Assembly-CSharp.dll. I updated pegasus.json, replaced the 2 decrypted dlls as well as the undecrypted Assembly-CSharp.dll, and than the patching worked.

But got "Hearthstone has been updated! Please download the latest version." when launch the game.


cheers

**Comment by huanged** [comment]
I've successfully dectyped Assembly-CSharp.dll, but got "Index was outside the bounds of the array" in the Inject method


System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Mono.Cecil
  StackTrace:
   at Mono.Cecil.PE.ByteBuffer.ReadUInt16()
   at Mono.Cecil.PE.ImageWriter.PatchResourceDirectoryTable(ByteBuffer resources)
   at Mono.Cecil.PE.ImageWriter.PatchResourceDirectoryEntry(ByteBuffer resources)
   at Mono.Cecil.PE.ImageWriter.PatchResourceDirectoryTable(ByteBuffer resources)
   at Mono.Cecil.PE.ImageWriter.BuildSections()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName)
   at Hearthrock.Client.Hacking.Patcher.Inject() in D:\software\hearthrock\hearthrock-master\src\Hearthrock.Client\Hacking\Patcher.cs:line 139
   at Hearthrock.Client.Hacking.Patcher.<InjectAsync>b__13_0() in D:\software\hearthrock\hearthrock-master\src\Hearthrock.Client\Hacking\Patcher.cs:line 107
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
